/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chair1.glb 
Author: Andy.Honor (https://sketchfab.com/Andy.Honor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bar-cafe-furniture-bar-chair-74715073e76c4206afeab1ce070921a2
Title: Bar & Cafe Furniture - Bar chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chair1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Foregrou} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.FrontCol} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Silver_B} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.wood} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Silver_B} />
      </group>
    </group>
  )
}

useGLTF.preload('/chair1.glb')
