/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\lamp2.gltf 
Author: Clums Paint&Prints (https://sketchfab.com/Callum.Lloyd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laval-lamp-511916cc121a48b0ba44e789f187ba12
Title: laval lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/lamp2.gltf')
  const group=useRef();
  const {  currentColor } = useCharacterAnimations();
  let scl=[0.05,0.05,0.05]
  let rots=[0,0,0]
  let pos=[0,-1.76,0]
  if(props.lamp2)
  {
    rots=props.rotation;
    scl=props.scale
    pos=props.position
  }
  return (
    <group ref={group} position={pos} rotation={rots} scale={scl} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 24.958, 0]}>
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.lambert2} 
               material-color={currentColor}
            />
            <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.lambert3} 
               material-color={currentColor}
            />
          </group>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert4} position={[-19.972, 37.743, -15.719]} rotation={[0, 0, -1.063]} scale={0.822} 
             material-color={currentColor}
          />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert4} position={[-19.651, 6.431, -7.43]} rotation={[-0.764, 0, 0]} scale={0.861} 
             material-color={currentColor}
          />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert4} position={[-19.079, 18.468, -8.938]} scale={0.738} 
             material-color={currentColor}
          />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert4} position={[-16.063, 53.389, -10.729]} rotation={[0, 0, -1.063]} scale={0.822} 
             material-color={currentColor}
          />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.lambert4} position={[-27.222, 10.173, -7.405]}
           material-color={currentColor} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.lambert5} position={[0, 30.183, 0]} scale={0.766} 
             material-color={currentColor}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/lamp2.gltf')
