/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\lamp2.gltf 
Author: Clums Paint&Prints (https://sketchfab.com/Callum.Lloyd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laval-lamp-511916cc121a48b0ba44e789f187ba12
Title: laval lamp
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/lamp2-transformed.glb')
  const group=useRef();
  const {  currentColor } = useCharacterAnimations();
  let scl=[0.05,0.05,0.05]
  let rots=[0,0,0]
  let pos=[0,-1.76,0]
  if(props.lamp2)
  {
    rots=props.rotation;
    scl=props.scale
    pos=props.position
  }
  return (
    <group ref={group} position={pos} rotation={rots} scale={scl} {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert4} position={[-19.972, 37.743, -15.719]} rotation={[0, 0, -1.063]} scale={0.822} 
  material-color={currentColor}
      />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert5} position={[0, 30.183, 0]} scale={0.766} 
  material-color={currentColor}
      />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert2} position={[0, 24.958, 0]}
      material-color={currentColor} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert3} position={[0, 24.958, 0]} 
material-color={currentColor}
      />
    </group>
  )
}

useGLTF.preload('/model/lamp2-transformed.glb')
