/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lamp1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const group=useRef();
  const {  Color } = useCharacterAnimations();
  let scl=[3,3,3]
  let rots=[0,0,0]
  let pos=[0,-1.3,0]
  if(props.lamp1)
  {
    rots=props.rotation;
    scl=props.scale
    pos=props.position
  }
  const { nodes, materials } = useGLTF('/model/lamp1.glb')
  return (
    <group ref={group} {...props} position={pos} rotation={rots} scale={scl} dispose={null}>
      <group >
        <mesh geometry={nodes.light.geometry} material={materials.Lamp} />
        <mesh geometry={nodes.Table_Lamp_fabric.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.Table_Lamp_fabric_rim.geometry} material={materials['Old White Metal']} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Porcelain} 
          material-color={Color}
        />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Porcelain Blue']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lamp1.glb')
