/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lamp1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const group=useRef();
  const {  Color } = useCharacterAnimations();
  const {  Rotate } = useCharacterAnimations();

  const { nodes, materials } = useGLTF('/model/lamp1.glb')
  return (
    <group ref={group} {...props} rotation={[0,Rotate.x,0]} scale={[0.5,0.5,0.5]} dispose={null}>
      <group scale={5}>
        <mesh geometry={nodes.light.geometry} material={materials.Lamp} />
        <mesh geometry={nodes.Table_Lamp_fabric.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.Table_Lamp_fabric_rim.geometry} material={materials['Old White Metal']} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Porcelain} 
          material-color={Color}
        />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Porcelain Blue']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lamp1.glb')
