/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: VX-Designs (https://sketchfab.com/vxdesigns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/single-sofa-free-ec2c92de034242e884a7a6476763077a
Title: Single Sofa (FREE)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const group=useRef();
  const {  currentColor } = useCharacterAnimations();
  let scl=[1.5,1.5,1.5]
  let rots=[0,-3.1,0]
  let pos=[0,-1.3,0]
  if(props.sofa2)
  {
    rots=props.rotation;
    scl=props.scale
    pos=props.position
  }
  const { nodes, materials } = useGLTF('/model/sofa2.gltf')
  return (
    <group ref={group} rotation={rots}  scale={scl} position={pos} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.304}>
        <mesh geometry={nodes.Object_3.geometry} material={materials['None_Base_Diffuse.png']}
        material-color={currentColor} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['None_Texture.jpg']} 
          material-color={currentColor}
        />
        <mesh geometry={nodes.Object_5.geometry} material={materials['None_Texture.jpg']} 
          material-color={currentColor}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/sofa2.gltf')
