/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sofa1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/sofa1.glb')
  const group=useRef();
  const {  Color } = useCharacterAnimations();
  const {  Rotate } = useCharacterAnimations();
  return (
    <group ref={group} scale={[0.6,0.6,0.6]} rotation={[0,Rotate.x,0]}  dispose={null}>
      <mesh geometry={nodes.Foot.geometry} material={materials.Black} position={[-0.38, 0.044, -1.551]} />
      <mesh geometry={nodes.pillow4.geometry} material={materials.Sofa_Fabric} position={[0.095, 0.581, 0.816]} rotation={[-3.102, 0.977, -1.177]} 
        material-color={Color}
      />
      <mesh geometry={nodes.Sofa.geometry} material={materials.Sofa_Fabric} position={[-0.141, 0.14, -1.094]} />
      <mesh geometry={nodes.sofa_back.geometry} material={materials.Sofa_Fabric} position={[-0.141, 0.14, -1.094]} />
      <mesh geometry={nodes.sofa_cusion.geometry} material={materials.Sofa_Fabric} position={[-0.141, 0.14, -1.094]} />
      <mesh geometry={nodes.sofa_side.geometry} material={materials.Sofa_Fabric} position={[-0.141, 0.14, -1.094]} />
    </group>
  )
}

useGLTF.preload('/sofa1.glb')
