/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 table1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from "../../contexts/ModelControl";

export default function Model(props) {
  const group=useRef();
  let {  Color } = useCharacterAnimations();
  const {Rotate} =useCharacterAnimations();

  const { nodes, materials } = useGLTF('/model/table1.glb')
  return (
<group ref={group} {...props} rotation={[0,Rotate.x,0]} dispose={null}>
      <mesh geometry={nodes.legs.geometry} material={materials['Material.001']} position={[0.154, 0.416, -0.109]} 
        material-color={Color}
      />
      <mesh geometry={nodes.supports.geometry} material={materials['Material.001']} position={[-0.096, 0.114, 0]} 
    material-color={Color}

      />
      <mesh geometry={nodes.table_bottom_support.geometry} material={materials['Material.001']} position={[0, 0.416, 0.064]} 
    material-color={Color}

      />
      <mesh geometry={nodes.table_top003.geometry} material={materials['Material.001']} position={[0, 0.458, 0]}
    material-color={Color}
       />
    </group>
  )
}

useGLTF.preload('/table1.glb')
